### ISSUE TITLE
Erreur 404

### ISSUE THREAD

**Issue by dandan2611** [TheShark34/S-Update-Server#13]
Bonjour, il y a peu que je suis votre série sur S-Update (Launcher minecraft)
J'ai un bug assez dérangeant :
- J'ai téléchargé la dernière version de S-Update, 3.1.0  je l'ai installée dans mon hébergement web et quand je me connecter à mon serveur avec internet : Adresse **/worldnations/launcher/** il me redirige vers    Adresse **/worldnations/launcher/panel** et bien sur vu qu'il n'existe pas ! **Erreur 404**

Merci de m'aider au plus vite !

**Comment by Litarvan** [comment]
http://support.manercraft.fr/ (indiqué sur le serveur Discord de support au passage)
