### ISSUE TITLE
Erreur dans le code

### ISSUE THREAD

**Issue by Bricklou** [TheShark34/S-Update-Server#14]
Dans le code de la release de S-Update-Server 3.1.0, il y a une erreur dans le code. Dans le src/routes.php à la ligne 28:
`return new RedirectResponse("panel");`
doit être changé en:
`return new RedirectResponse("index.php/panel");`

Cordialement Bricklou

**Comment by Litarvan** [comment]
Ce n'est pas une erreur, c'est simplement qu'il faut l'extension mod_rewrite pour éviter ça, bien sur l'extension n'est pas requise vu qu'on peut contourner simplement en allant sur /index.php/

Evidemment, dans les prochaines versions, la présence de cette extension sera vérifiée pour rediriger sur l'URL qu'il faut.
