### ISSUE TITLE
"Exception : BadServerResponseException"

### ISSUE THREAD

**Issue by MomoCrash** [TheShark34/S-Update-Server#19]
Version : 1.7.10
On est un lancement ExternalLaunchProfile
Les assets et libs et natives sont bonne .
Le site de S-Update contient PHP et apache 2.4  (surment d'autres)

Le crash complet :
https://hastebin.com/wisamoramu.shell
Le code n'a jamais eu d'erreur ceci se produit depuis que je suis passer sur hébergeur Payant (Dedigo)

**Comment by Litarvan** [comment]
Le fichier files/mods/MégaMod+.jar a un accent, enlève le et ça sera réglé :)
