### ISSUE TITLE
Page Blanche

### ISSUE THREAD

**Issue by nonoland** [TheShark34/S-Update-Server#2]
Bonjour,
Qu'elle extension php faut-il installé pour faire fonctionner ceci car il m'affiche une page blanche :D

**Comment by TheShark34** [comment]
Normalement aucune, sur quel hebergeur es tu ?

**Comment by nonoland** [comment]
J'heberge moi même le serveur web sur un VPS Debian utilisant Apache.
Et oui j'ai pris la version 3.

**Comment by TheShark34** [comment]
Vérifie si le Rewrite Engine est activé sur Apache, et retélécharge le serveur 3 je l'ai mis à jour récemment.

**Comment by nonoland** [comment]
Le Rewrite Engine était déjà activé, j'ai retélécharger le serveur mais il m'affiche toujours une page blanche :(

**Comment by TheShark34** [comment]
Ha, tu es sur que l'extension mod_rewrite est là ?

**Comment by nonoland** [comment]
oui

**Comment by nonoland** [comment]
En vérifiant le index.php j'ai remarquer qu'il manque le dossier vendor :D

**Comment by TheShark34** [comment]
Attends, me dis pas que tu as cloné le repo ? Il faut aller dans releases et prendre le zip s-update-server !

**Comment by nonoland** [comment]
Désolé je croyais qu'il fallait prendre le repo entier. Je suis pas habitué à Github :)
