### ISSUE TITLE
Problème FileDeleter

### ISSUE THREAD

**Issue by Kakumi** [TheShark34/S-Update-Server#23]
Bonjour :)

J'ai un petit problème pour mon launcher, j'ai mis le ce que je ne souhaite pas supprimé dans ignore.list, j'ai mis la liste en 777 et la version est en 3.1.0, pourtant les fichiers sont quand même remplacé par ceux sur le FTP, comme si il ne prenais pas en compte le fichier, pourtant il le charge bien j'ai essayé de modifier la source ou quoi…

**Comment by Litarvan** [comment]
Laisse moi deviner, les fichiers en question ce sont des options par exemple que tu as mis dans le dossier files/ ?

**Comment by Kakumi** [comment]
oui options.txt mais aussi saves/, launcher.properties

**Comment by Litarvan** [comment]
C'est pas comme ça que tu dois faire, tu dois télécharger manuellement les fichiers sinon lui il va les retélécharger lors d'une modification si tu les mets dans le files/
