### ISSUE TITLE
Avec site sur raspberry

### ISSUE THREAD

**Issue by Reithsaw** [TheShark34/S-Update-Server#24]
Bonjour alors voilà je sais c'est un vieux tuto etc, mais quand je veux aller sur mon site qui est héberger sur mon raspberry, j'ai cette erreur là :
. */ // Checking if(!is_dir(__DIR__ . '/vendor')) { echo "
BLEH, il faut telecharger S-Update-Server depuis la page release du repo Github !
"; echo "ICI !"; die(); } // Just loading all require_once __DIR__ . '/vendor/autoload.php'; require_once "src/bootstrap.php"; ?>

**Comment by Litarvan** [comment]
Il te manque PHP tout simplement
