### ISSUE TITLE
404 error server/is-enabled

### ISSUE THREAD

**Issue by kileurf** [TheShark34/S-Update-Server#28]
Bonjour,

je suis en train de monter mon launcher et lorsque j'essaie d'utiliser ta librairie S-update avec le serveur S-update-server (librairie version  3.1.0 et server 3.1.0) au moment de la connection au serveur pour le téléchargement des fichiers, celui-ci tente d'aller dans : /html/server/is-enabled

mais cela n'existe pas sur le serveur

faut-il ajouter le path <path_server>/html/server/is-enabled et si oui, qu'est ce qui doit être mis dans le fichier (j'ai cru voir qu'il fallait du json)

Merci d'avance

edit: le dossier server avec tous les check n'a pas été créé

**Comment by Litarvan** [comment]
La réponse est que la FAQ : http://support.maner.fr/
