### ISSUE TITLE
Je n'arrive pas a aller sur la page d'installation.

### ISSUE THREAD

**Issue by steakmans** [TheShark34/S-Update-Server#29]
Bonjour depuis a peux près une semaine j’essaie de configurer S-update serveur et je n'arrive pas a aller sur la page de configuration. Pourriez vous m'aider.
L'erreur est : Not Found
The requested URL was not found on this server. 

Voila et merci d'avance.

**Comment by Litarvan** [comment]
Il faut aller sur /index.php/panel comme indiqué sur https://support.maner.fr/
