### ISSUE TITLE
Erreur

### ISSUE THREAD

**Issue by BlackScarx** [TheShark34/S-Update-Server#3]
J'ai uploadé tout le dossier et quand je me rend sur le site j'ai ceci
Fatal error: Class 'Paladin\Page' not found in /home/u479651411/public_html/Login/Login.php on line 31

**Comment by TheShark34** [comment]
D'accord, est-tu sur d'avoir pris la version qui est dans releases ? Je pense que tu as cloné le git.
C'est ici qu'il faut le télécharger : https://github.com/TheShark34/S-Update-Server/releases

**Comment by TheShark34** [comment]
Réglé via skype !
