### ISSUE TITLE
Problème lors de la sélection du mot de passe.

### ISSUE THREAD

**Issue by steakmans** [TheShark34/S-Update-Server#30]
Bonjour,
Depuis quelques temps je suis votre tutoriel pour créer un launcher et au moment de configurer S update, les drapeaux ne s'affichent pas et j'arrive directement sur la page de sélection de mot de passe. Je sélectionne mon mot de passe et cela me redirige sur la même page mais les champs de texte son vide et rien n'a été pris en compte.
Que puis je faire, merci d'avance.

**Comment by skrilax91** [comment]
Bonjour, cela m'arrive également, je pense que c'est un problème au niveau de javascript

**Comment by Litarvan** [comment]
Comme indiqué sur la FAQ, c'est que les permissions du dossier config ne sont pas bonnes, mettez le groupe www-data en owner et les permissions 660 en recursif sur le dossier config/ du serveur s-update
(Et la page sert à définir le mot de passe)

**Comment by steakmans** [comment]
Bonjour Litarvan, 

J'ai essayé votre solution mais toujours le même problème.

Merci.
(Pour information j'ai php 7.2.24 apache 2.4.29 et je suis sur ubuntu serveur 18.04.3.)

**Comment by Litarvan** [comment]
Salut, tu es sûr que le dossier config et son contenu sont en 660, et que www-data est le groupe possesseur ? Les commandes pour faire ça sont :
```
chown -R :www-data /var/www/chemin/du/dossier/config
chmod -R 660 /var/www/chemin/du/dossier/config
```
Si tu es sûr, lâche un : 
```
ls -lah /var/www/chemin/du/dossier/config
```
Puis screen moi le résultat

**Comment by skrilax91** [comment]
Il est possible aussi que ton mot de passe n’ai pas les requirement, j’ai modifier mon premier mot de passe par un mot de passe (qui est le même) avec un chiffre et ça a fonctionné
