### ISSUE TITLE
Problème avec l'install du serveur

### ISSUE THREAD

**Issue by Ranily57** [TheShark34/S-Update-Server#35]
Quand je rentre le mot de passe dans les deux cases prévue à cet effet et que je clique sur "start", la page ne change pas et il enlève mes mot de passe ! 

Est ce qu'il y aurais un soucis dans le code que je peux modifier rapidement ?

**Comment by Ranily57** [comment]
En fait j'ai trouver le soucis, faite `chmod -R 777 supdate` sur tout votre dossier S-Update, ca règleras le soucis :)

**Comment by Litarvan** [comment]
Utilise plutôt 660 et vérifie que le groupe possesseur soit "www-data", c'est bien plus sécurisé
