### ISSUE TITLE
Panel introuvable

### ISSUE THREAD

**Issue by DatPenguin** [TheShark34/S-Update-Server#4]
Salut et avant tout merci pour ton tutoriel concernant les launchers Minecraft, il est très complet, mais c'est justement en le suivant que j'ai eu un petit problème.

En effet, je suis arrivé à la phase concernant S-Update, partie cloud, et là je n'ai d'abord pas réussi à trouver installer.php . J'ai donc téléchargé deux .zip : le master et le release, que j'ai décompressé dans de nouveaux dossiers spécialement créés pour l'occasion sur mon Wamp. En accédant au master, il me dit de télécharger la release, et en accédant à la release, le message suivant apparaît : The requested URL /monsite/s-update-server-3.1.0/panel was not found on this server.

Aurais-tu une solution? Merci

P.S.: Je suis sous Windows 10 x64

**Comment by TheShark34** [comment]
Alors il faut aller sur index.php/ (avec le / a la fin) et au passage, tu devras rajouter, après : SUpdate su = new SUpda........
su.getServerRequester().setRewriteEnabled(true);
C'est juste une des fonctions qui marche pas sur ton hebergeur.
Au passage, suit plutôt les tutos vidéos ils sont à jour eux ! : Cherche TheShark34 sur YT

**Comment by DatPenguin** [comment]
Merci, le slash en plus fonctionne !

Mais pour ce qui est du su.getServerRequester().setRewriteEnabled(true); , cela me donne une erreur: Description	Resource	Path	Location	Type
The method getServerRequester() is undefined for the type SUpdate.

Est-ce une méthode que je devrai déclarer moi-même, du coup?

Merci encore de ta réponse rapide !

**Comment by TheShark34** [comment]
Non, sinon c'est que tu as pris la version 2 de supdate, il faut la 3 !

**Comment by DatPenguin** [comment]
En effet, j'avais pris la version donnée sur le forum Bukkit ^^' Merci :)
