### ISSUE TITLE
Impossible d'installer S-Update-Server

### ISSUE THREAD

**Issue by Bricklou** [TheShark34/S-Update-Server#6]
Bonjour, je voulais installer ton logiciel son mon ordinateur (raspbian ou debian sur raspberry pi 2) mais j'ai une erreur 500 qui s'affiche. J'ai essayé de regarder le code source mais je n'ai pas trouvé. Pouvez-vous m'aider ?

Cordialement,
Bricklou

**Comment by TheShark34** [comment]
Il me faut les logs apache

**Comment by Bricklou** [comment]
Le voilà: http://1drv.ms/1Y9Er0p

**Comment by TheShark34** [comment]
Supprime le fichier .htaccess
Tu devras aller sur index.php/ (avec un / a la fin)
Aussi dans ton code, après SUpdate su = new SU............... Tu devras mettre su.getServerRequester().setRewriteEnabled(true);

Voilà en esperant avoir pu t'aider !

**Comment by ilyanfraimbault** [comment]
Moi j'ai bien tout installer mais il m'affiche cela je ne comprend pas mon ftp c'est free et j'utilise comme ftp client ClassicFtp je suis sur mac

**Comment by Bricklou** [comment]
Sur free, PHP n'est pas à jours.
